url: http://tp/

# Where things are
source: _site/
destination: public_html/
collections:
  army_lists:
    output: true
    permalink: army-lists/:title.html
  forces:
  special_rules:
  units:
  weapons:

# Conversion
markdown: kramdown

# Outputting
defaults:
  -
    scope:
      path: ''
    values:
      layout: default
  -
    scope:
      path: ''
      type: army_lists
    values:
      layout: army_list

kramdown:
  enable_coderay: false
  parse_block_html: true
  toc_levels: 1..3