url: http://localhost:4000/

# Where things are
source: _site/
destination: public_html/
collections:
  - army_lists
  - forces
  - special_rules
  - units
  - weapons

# Plugins
gems: ['jekyll-less']

# Conversion
markdown: kramdown

# Outputting
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'

kramdown:
  enable_coderay: false
  parse_block_html: true
  toc_levels: 1..3